name: Deploy FastAPI Project

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Application
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > privatekey.pem
          chmod 600 privatekey.pem

          trap "rm -f privatekey.pem" EXIT

          ssh -o StrictHostKeyChecking=no -i privatekey.pem ${USER_NAME}@${HOST_NAME} '
            cd ~/task2 || { echo "Failed to navigate to ~/task2"; exit 1; }
            git pull || { echo "Failed to pull latest code"; exit 1; }

            source venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }
            pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }

          
            ps aux | grep [u]vicorn | awk '\''{ print $2 }'\'' | xargs kill -HUP
          '
