name: Test FastAPI Project 

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Virtual Environment
        run: python -m venv venv

      - name: Install Dependencies
        run: source venv/bin/activate && pip install -r requirements.txt

      - name: Run Test
        run: source venv/bin/activate && pytest
